accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (login,logout,password_reset,password_reset_done,password_reset_confirm,
	password_reset_complete
	)
#from accounts.views import ProfileView
app_name='accounts'
urlpatterns=[
		 url(r'^$',views.home),

		 url(r'^login/$',login,{'template_name': 'accounts/login.html'}), 
		 url(r'^logout/$',logout,{'template_name': 'accounts/logout.html'}), 
		 url(r'^register/$' ,views.register,name='register'),
		 url(r'^profile/$' ,views.view_profile,name = 'view_profile'),
		# url(r'^profile/$' ,ProfileView.as_view(),name = 'ProfileView'),
		 url(r'^profile/edit/$',views.edit_profile,name= 'edit_profile'),
		 url(r'^change-password/$',views.change_password,name='change_password'),
		 url(r'^reset-password/$',password_reset,{'template_name':'accounts/reset_password.html','post_reset_redirect':'accounts:password_reset_done','email_template_name':'accounts/reset_password_email.html'},name='reset-password'),
		 url(r'^reset-password/done/$',password_reset_done,{'template_name':'accounts/reset_password_done.html'},name='password_reset_done'),
		 url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
		 password_reset_confirm,{'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),
		 url(r'^reset-password/complete/$',password_reset_complete,name='password_reset_complete')


	]

	

hospital/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from hospital import views

urlpatterns = [
    url(r'^$',views.login_redirect, name='login_redirect'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    #url(r'^logout/$', 'accounts.views.logout'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User)
	description = models.CharField(max_length = 100,default ='')
	city = models.CharField(max_length = 100,default = '')
	website = models.URLField(default='')
	phone = models.IntegerField(default=0)


	def __str__(self):
	 	return self.user.username

def create_profile(sender, **kwargs):
	if kwargs['created']:
			user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender = User) 

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm


class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required = True)

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
			)

		def save(self,commit = True):
			user = super(RegistrationForm ,self).save(commit = False)
			user.first_name = self.cleaned_data['first_name']
			user.last_name = self.cleaned_data['last_name']
			user.email = self.cleaned_data['email']


			if commit:
				user.save()


			return user



class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields = (
			'email',
			'first_name',
			'last_name',
			'password'
			)
# class ProfileForm(forms.Form):
# 	#user = forms.OneToOneField(User)
# 	description = forms.CharField(max_length = 100)
# 	city = forms.CharField(max_length = 100)
# 	website = forms.CharField()
# 	phone = forms.IntegerField()

accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import (
	RegistrationForm,
	EditProfileForm
	)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
# from django.contrib.auth.decorators import 
from django.views.generic import TemplateView
from django.shortcuts import render
#from accounts.forms import ProfileForm
#from accounts.models import UserProfile
from django.contrib.auth.decorators import login_required

# class ProfileView(TemplateView):
# 	template_name='accounts/profile.html'

# 	def get(self,request):
# 		form=ProfileForm()
# 		return render(request, self.template_name,{'form':form})

# Create your views here.

def home(request):
	numbers = [1,2,3,4,5]
	name = 'Milan'

	args = {'myName':name, 'numbers':numbers}
	return render(request,'accounts/home.html')


def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/accounts')
	else:
		form = RegistrationForm()


	args = {'form': form }
	return render(request, 'accounts/reg_form.html',args)

# def logout(request):
# 	auth_logout(request)
# 	return redirect('/')
 	
 	

     
     

@login_required
def view_profile(request):
	args = {'user':request.user}
	return render(request,'accounts/profile.html',args)

@login_required
def edit_profile(request):
	if request.method == "POST":
		form = EditProfileForm(request.POST,instance=request.user)


		if form.is_valid():
			form.save()
			return redirect('/accounts/profile')
		
		

	else:
		form = EditProfileForm(instance=request.user)

	args = {'form':form}
	return render(request,'accounts/edit_profile.html',args)


def change_password(request):
	if request.method == "POST":
		form = PasswordChangeForm(data=request.POST,user=request.user)


		if form.is_valid():
			form.save()
			update_session_auth_hash(request,form.user)
			return redirect('/accounts/profile')
		else:
			return redirect('accounts/change_password')
	
	else:
		form = PasswordChangeForm(user = request.user)

	args = {'form':form}
	return render(request,'accounts/change_password.html',args)


# def edit_userprofile(request):
# 	if request.method == 'POST':
# 		form = UserChangeForm(request.POST)

hospital/views.py
from django.shortcuts import redirect

def login_redirect(request):
	return redirect('/accounts/login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}



{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
	</form>
	<br>
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}



{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
	</form>
	<br>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
<h1>Home</h1>
{% block head %}

{% endblock %}

{% block body %}
<h1>Hi,{{ user }}</h1>

<title>Home</title>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */ 
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */ 
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>

<div class="jumbotron">
  <div class="container text-center">
    <h1>Treasure to the Hostelites</h1>      
    <p>Food Clothing and Shelter</p>
  </div>
</div>

<br>
<br>
<br>
<br>

<div class="container">    
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>
      </div>
      <a href="/accounts/logout" onclick="signOut();">Sign out</a>
<script>
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
    });
  }
</script>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-danger">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-success">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>
      </div>
    </div>
  </div>
</div><br>

<div class="container">    
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-primary">
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>
      </div>
    </div>
  </div>
</div><br><br>

<!-- <footer class="container-fluid text-center">
  <p>Online Store Copyright</p>  
  <form class="form-inline">Get deals:
    <input type="email" class="form-control" size="50" placeholder="Email Address">
    <button type="button" class="btn btn-danger">Sign Up</button>
  </form>
</footer> -->

</body>
</html>

{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
<h1>Welcome to the Login page</h1>
<p>
	You Can log in here!!!
</p>
<h2>Login</h2>
<form method="post">
	{% csrf_token %}
	{{  form.as_p }}
	<button type="submit">Login</button>
	<p><strong>-- OR --</strong></p>
  <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
<!--   <p><strong>-- OR --</strong></p>
  <p><strong>-- OR --</strong></p>
  <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br> -->
</form>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
<h1>You have been logged out </h1>
<p>
	want to log in again
</p>
<h2>Login</h2>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container">
	<div class="row">
		<div class="col-sm-4 col-md-4 user-details">
            <div class="user-image">
                <img src="http://www.gravatar.com/avatar/2ab7b2009d27ec37bffee791819a090c?s=100&d=mm&r=g" alt="Karan Singh Sisodia" title="Karan Singh Sisodia" class="img-circle">
            </div>
            <div class="user-info-block">
                <div class="user-heading">
                    <h3>{{ user.first_name }} {{user.last_name}}</h3>
                    <span class="help-block">{{ user.userprofile.city }}</span>
                </div>
                <ul class="navigation">
                    <li class="active">
                        <a data-toggle="tab" href="#information">
                            <span class="glyphicon glyphicon-user"></span>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tab" href="/accounts/profile/edit">
                            <span class="glyphicon glyphicon-cog"></span>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tab" href="#email">
                            <span class="glyphicon glyphicon-envelope"></span>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tab" href="#events">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </a>
                    </li>
                </ul>
                <div class="user-body">
                    <div class="tab-content">
                        <div id="information" class="tab-pane active">
                            <h4>Account Information</h4>
                            <h6>{{ user.email }}</h6>
                        </div>
                        <div id="settings" class="tab-pane">
                            <h4>Settings</h4>
                        </div>
                        <div id="email" class="tab-pane">
                            <h4>Send Message</h4>
                        </div>
                        <div id="events" class="tab-pane">
                            <h4>Events</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<style>
	body {background: #EAEAEA;}
.user-details {position: relative; padding: 0;}
.user-details .user-image {position: relative;  z-index: 1; width: 100%; text-align: center;}
 .user-image img { clear: both; margin: auto; position: relative;}

.user-details .user-info-block {width: 100%; position: absolute; top: 55px; background: rgb(255, 255, 255); z-index: 0; padding-top: 35px;}
 .user-info-block .user-heading {width: 100%; text-align: center; margin: 10px 0 0;}
 .user-info-block .navigation {float: left; width: 100%; margin: 0; padding: 0; list-style: none; border-bottom: 1px solid #428BCA; border-top: 1px solid #428BCA;}
  .navigation li {float: left; margin: 0; padding: 0;}
   .navigation li a {padding: 20px 30px; float: left;}
   .navigation li.active a {background: #428BCA; color: #fff;}
 .user-info-block .user-body {float: left; padding: 5%; width: 90%;}
  .user-body .tab-content > div {float: left; width: 100%;}
  .user-body .tab-content h4 {width: 100%; margin: 10px 0; color: #333;}
</style>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Register</button>
</form>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
	<h1>Password Reset</h1>
	<p>
		Forgotten your password? Enter your email address below and we will email the instruction below to set the password for the new one.
	</p>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Reset Password</button>

	</form>

	
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
	<h1>Password Reset</h1>
	<p>
		We have emailed you the instruction for setting up the new password if the emal id exits
		with the email you entered . You should recieve them shortly.

		If you dont recieve an email , please make sure you have enetered the correct email address,Check ypur spam folder

	</p>
	
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receving this email because you requested a password for your account at {{ site.name }}.{% endblocktrans %}

{% trans "Please go to the following page and a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you have forgetten:" %} {{ user.get_username }}

{% trans " Thanks for using the site !" %}
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}

accounts/templates/base.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


	<title>Hello world</title>
<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<meta charset="utf-8">

	<title></title>
	{% endblock %}
	
</head>
<body>

	    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
              <li class="active"><a href="/accounts">Home</a></li>
           <!--   <li><a href="/accounts/login">Login</a></li>-->
              <li><a href="/accounts/logout">Logout</a></li>
              <li><a href="/accounts/profile">Profile</a></li>
              <li><a href="/accounts/profile/edit">Settings</a></li>
              <li><a href="/accounts/change-password">Change Password</a></li>
             
              
              
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <h4>Hi,{{ user }}</h4>
            </ul>
           
            {% else %}

            <ul class="nav navbar-nav">
              
               <li><a href="/accounts/reset-password">Reset Password</a></li>
             
            
              
              
            </ul>
            <ul class="nav navbar-nav navbar-right">
               <li><a href="/accounts/login">Login</a></li>
              
              
              <li><a href="/accounts/register">Register</a></li>
            </ul>
            {% endif %}
            
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
	<h1></h1>
	{% block body %}

	{% endblock %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
  <div id="footer">
    <div class="container-footer">
        <div class="row">
            <h3 class="footertext">About Us:</h3>
            <br>
              <div class="col-md-4">
                <center>
                  <img src="http://oi60.tinypic.com/w8lycl.jpg" class="img-circle" alt="the-brains">
                  <br>
                  <h4 class="footertext">Programmer</h4>
                  <p class="footertext">You can thank all the crazy programming here to this guy.<br>
                </center>
              </div>
              <div class="col-md-4">
                <center>
                  <img src="http://oi60.tinypic.com/2z7enpc.jpg" class="img-circle" alt="...">
                  <br>
                  <h4 class="footertext">Artist</h4>
                  <p class="footertext">All the images here are hand drawn by this man.<br>
                </center>
              </div>
              <div class="col-md-4">
                <center>
                  <img src="http://oi61.tinypic.com/307n6ux.jpg" class="img-circle" alt="...">
                  <br>
                  <h4 class="footertext">Designer</h4>
                  <p class="footertext">This pretty site and the copy it holds are all thanks to this guy.<br>
                </center>
              </div>
            </div>
            <div class="row">
            <p><center><a href="#">Contact Stuff Here</a> <p class="footertext">Copyright 2014</p></center></p>
        </div>
    </div>
</div>
<style>
html {
  position: relative;
  min-height: 100%;
}
body {
   Margin bottom by footer height 
  margin-bottom: 60px;
}
#footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 280px;
  background: 
  /* color overlay */ 
    linear-gradient(
      rgba(240, 212, 0, 0.45), 
      rgba(0, 0, 0, 0.45)
    ),
    /* image to overlay */
    url(http://images.cdn.fotopedia.com/_avPIZmqM3w-7z161LH_268-hd.jpg);
}


/* Custom footer CSS
-------------------------------------------------- */

.container-footer {
  width: auto;
  max-width: 680px;
  padding: 0 15px;
}
.container .text-muted {
  margin: 20px 0;
}
.footertext {
  color: #ffffff;
}


</style>
  <!--Footer-->

</body>
</html>